%{
	#include<stdio.h>
%}

%token NUMBER ID FUNC_NAME COMMAND TRUE FALSE RETURN CALL SCAN PRINT ISFILE ISDIR EXISTS RAWBASH RAWBATCH BASH BATCH LOADENV NL EPSILON TEXT BREAK CONTINUE BEGIN_UX END_UX BEGIN_WN END_WN IF ELSE ELIF FUNC IN FOR WHILE READFILE DIR

%%

stmt:N '\n'
N:NUMBER 

%%

void main(){
	printf("Enter the string");
	yyparse();
}
